name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
      
      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Inject API Keys
        run : |
          AzureConstantsFile=`find . -name DocumentDbConstants.cs | head -1`
          echo AzureConstantsFile = $AzureConstantsFile

          sed -i '' "s/#error Missing Keys/\/\/#error Missing Keys/g" "$AzureConstantsFile"
          
      - name: Build Android App
        run: |                    
          msbuild ./CosmosDbSampleApp.Droid/CosmosDbSampleApp.Droid.csproj /verbosity:normal /p:Configuration=Release
